# Official python run time as a parent image
FROM python:3.11.4-slim

# Create user
RUN addgroup --system --gid 1001 flask && \
    adduser --system --uid 1001 app

# Set the working directory in the container
WORKDIR /app

# Copy directory into working directory
COPY . /app
# Install packages from requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Set user before runningz
USER app

# Expose port
EXPOSE 5000

# Use Flask entrypoint

# Run cmd to start the application
CMD ["python3", "app.py"]